Propogation of one inequality (Simon Dennis 19770235)
wvisser/green pull request #2
Opened 2018-08-04 08:11 UTC by denni9th

This code implements constant propogation of one variable

2018-08-12 17:13 UTC, Monkleys requested changes

2018-08-12 17:13 UTC, Monkleys commented on test/za/ac/sun/cs/green/service/canonizer/SATCanonizerTest.java
> +		check(o3, "(2<=2)&&(aa<2)", "1*v+-1<=0fail");
Please fix this `"(2<=2)&&(aa<2)", "1*v+-1<=0fail"`

2018-08-12 17:13 UTC, Monkleys commented on test/za/ac/sun/cs/green/service/simplify/OnlyConstantPropogationTest.java
> +        //props.setProperty("green.service.sat", "(canonize sink)");
Rather remove unused code than uncomment it.

2018-08-13 16:43 UTC, denni9th commented
@Monkleys added simplification and improved constant propogation

2023-01-07 07:54 UTC, closed without merging